### ISSUE TITLE
Mute event not being fired if call is not active

### ISSUE THREAD

**Issue by cdiscla** [gnaudio/jabra-browser-integration#49]
Hello, i'm integrating your lib in my webrtc web app and it works great.
I have only an issue: when the user clicks the mute button, it switches on, but i do not get any event in jabra.addEventListener(), i have tried to handle all events listed in source code.
It works fine with active call, but not if the user wants to mute the microphone even if the call is not active.
Is it the expected behavior or can it be solved?
I am currently using Jabra BIZ-2300
Thanks in advance and greetings

**Comment by jabra-slawaetz** [comment]
This is expected behaviour.

You are correct, mute only applies in a call (when headset is active and audio streaming is on)
The programming metaphor for the headsets follow the USB HID model (usb.org), where mute only applies when the device is offhook (active within a call).
According to the interaction model, then if the device is not active (offhook) then the microphone is not active, so the mute function does not apply.

**Comment by extmchristensen** [comment]
Closing, as question is answered and there has been no followup.
